[pytest]
# Default arguments:
# -v: verbose output (test names)
# -s: allow print() output in the console
# -n auto: run on all CPU cores (if pytest-xdist is installed)
# --tb=short: makes error reports shorter (shows only the failure location without long code traces)
addopts = -v -s --tb=short

# Indicate the root where our sources are located
pythonpath = .

markers =
    smoke
    regression
    images
    positive
    negative
    empty_state
    performance