[pytest]
# Default arguments:
# -v: verbose output (test names)
# -s: allow print() output in the console
# -n auto: run on all CPU cores (if pytest-xdist is installed)
# --tb=short: makes error reports shorter (shows only the failure location without long code traces)
addopts = -v -s --tb=short

# Make captured logs (including Allure pytest log attachments) include the same context fields.
log_format = %(levelname)s %(name)s:%(filename)s:%(lineno)d env=%(env)s worker=%(worker)s test=%(test_nodeid)s user=%(user_type)s req=%(request_id)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
# Упрощаем формат, чтобы системные логи не вызывали KeyError
;log_format = %(levelname)s %(name)s:%(filename)s:%(lineno)d %(message)s
;log_date_format = %Y-%m-%d %H:%M:%S

# Indicate the root where our sources are located
pythonpath = .

markers =
    smoke
    regression
    images
    positive
    negative
    empty_state
    performance