[pytest]
# 1. Базовые настройки запуска
# -s: позволяет видеть print() и системные логи в реальном времени
# -v: подробный вывод имен тестов
addopts = -v -s --tb=short

# 2. Настройки логирования (Упрощенные для отладки OTel)
# Мы временно выключаем кастомные поля (env, worker, req),
# так как внутренние логгеры OpenTelemetry о них не знают и могут "падать" при форматировании.
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(levelname)s %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Старый (сложный) формат пока "отдыхает" в комментариях:
# log_format = %(levelname)s %(name)s:%(filename)s:%(lineno)d env=%(env)s worker=%(worker)s test=%(test_nodeid)s user=%(user_type)s req=%(request_id)s %(message)s
# log_date_format = %Y-%m-%d %H:%M:%S

# 3. Пути и маркеры
pythonpath = .

markers =
    smoke
    regression
    images
    positive
    negative
    empty_state
    performance