name: API Regression Tests

# Описываем, когда запускать тесты
on:
  push:
    branches: [ main, master ] # При каждом пуше в эти ветки
  pull_request:
    branches: [ main, master ] # При создании PR
  workflow_dispatch:          # Позволяет запускать тесты вручную кнопкой в GitHub

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Tests
        # Связываем секреты GitHub с твоим кодом (os.getenv)
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          BASE_URL_PROD: ${{ secrets.BASE_URL_PROD }}
          X_API_KEY_PROD: ${{ secrets.X_API_KEY_PROD }}

          #user with history
          USER_PHONE_NUMBER_PROD: ${{ secrets.USER_PHONE_NUMBER_PROD }}
          USER_PASSWORD_PROD: ${{ secrets.USER_PASSWORD_PROD }}

          # user with empty history
          EMPTY_USER_PHONE_NUMBER_PROD: ${{ secrets.EMPTY_USER_PHONE_NUMBER_PROD }}
          EMPTY_USER_PASSWORD_PROD: ${{ secrets.EMPTY_USER_PASSWORD_PROD }}


          BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
          X_API_KEY_STAGE: ${{ secrets.X_API_KEY_STAGE }}

          USER_PHONE_STAGE: ${{ secrets.USER_PHONE_STAGE }}
          USER_PASS_STAGE: ${{ secrets.USER_PASS_STAGE }}
          EMPTY_USER_PHONE_STAGE: ${{ secrets.EMPTY_USER_PHONE_STAGE }}
          EMPTY_USER_PASS_STAGE: ${{ secrets.EMPTY_USER_PASS_STAGE }}


          ENV_TYPE: ${{ secrets.ENV_TYPE }}

          # Database
          DB_HOST_PROD: ${{ secrets.DB_HOST_PROD }}
          DB_PORT_PROD: ${{ secrets.DB_PORT_PROD }}
          DB_USER_PROD: ${{ secrets.DB_USER_PROD }}
          DB_PASSWORD_PROD: ${{ secrets.DB_PASSWORD_PROD }}
          DB_NAME_PROD: ${{ secrets.DB_NAME_PROD }}

          DB_HOST_STAGE: ${{ secrets.DB_HOST_STAGE }}
          DB_PORT_STAGE: ${{ secrets.DB_PORT_STAGE }}
          DB_USER_STAGE: ${{ secrets.DB_USER_STAGE }}
          DB_PASSWORD_STAGE: ${{ secrets.DB_PASSWORD_STAGE }}
          DB_NAME_STAGE: ${{secrets.DB_NAME_STAGE }}
        run: |
          pytest --alluredir=allure-results -n 2

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 10