name: API Smoke Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Global env settings
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-automation:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # turned on cashing dependencies from requirements.txt file

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Tests
        env:
          ENV_TYPE: ${{ secrets.ENV_TYPE }}
          BASE_URL_PROD: ${{ secrets.BASE_URL_PROD }}
          X_API_KEY_PROD: ${{ secrets.X_API_KEY_PROD }}

          # User with history
          USER_PHONE_NUMBER_PROD: ${{ secrets.USER_PHONE_NUMBER_PROD }}
          USER_PASSWORD_PROD: ${{ secrets.USER_PASSWORD_PROD }}

          # User with empty history
          EMPTY_USER_PHONE_NUMBER_PROD: ${{ secrets.EMPTY_USER_PHONE_NUMBER_PROD }}
          EMPTY_USER_PASSWORD_PROD: ${{ secrets.EMPTY_USER_PASSWORD_PROD }}

          # Stage Environment
          BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
          X_API_KEY_STAGE: ${{ secrets.X_API_KEY_STAGE }}
          USER_PHONE_STAGE: ${{ secrets.USER_PHONE_STAGE }}
          USER_PASS_STAGE: ${{ secrets.USER_PASS_STAGE }}
          EMPTY_USER_PHONE_STAGE: ${{ secrets.EMPTY_USER_PHONE_STAGE }}
          EMPTY_USER_PASS_STAGE: ${{ secrets.EMPTY_USER_PASS_STAGE }}

          # Database PROD
          DB_HOST_PROD: ${{ secrets.DB_HOST_PROD }}
          DB_PORT_PROD: ${{ secrets.DB_PORT_PROD }}
          DB_USER_PROD: ${{ secrets.DB_USER_PROD }}
          DB_PASSWORD_PROD: ${{ secrets.DB_PASSWORD_PROD }}
          DB_NAME_PROD: ${{ secrets.DB_NAME_PROD }}

          # Database STAGE
          DB_HOST_STAGE: ${{ secrets.DB_HOST_STAGE }}
          DB_PORT_STAGE: ${{ secrets.DB_PORT_STAGE }}
          DB_USER_STAGE: ${{ secrets.DB_USER_STAGE }}
          DB_PASSWORD_STAGE: ${{ secrets.DB_PASSWORD_STAGE }}
          DB_NAME_STAGE: ${{ secrets.DB_NAME_STAGE }}
        run: |
          pytest -m regression --alluredir=allure-results --junitxml=report.xml -n 2
#          If smoke tests failed, regression tests wouldn't be run
#          Regression tests will exclude smoke tests because "and not smoke"
#          pytest -m "regression and not smoke" --alluredir=allure-results -n 2

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 10

      - name: Load Allure history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clean history junk
        if: always()
        run: |
          if [ -d "gh-pages" ]; then
            cd gh-pages
            # Adding -A so to see hidden files like .env
            # Adding .nojekyll to the exception list  (GitHub needs it)
            ls -A | grep -vE '^[0-9]+$|history|index.html|last-history|favicon.ico|.nojekyll' | xargs rm -rf || true
            cd ..
          fi

      - name: Build Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
          force_orphan: true

      - name: Extract Test Stats
        if: always()
        run: |
            python -c "
            import xml.etree.ElementTree as ET
            import os
            try:
                tree = ET.parse('report.xml')
                root = tree.getroot()
#                Gathering statistics
                total = int(root.attrib.get('tests', 0))
                failures = int(root.attrib.get('failures', 0))
                errors = int(root.attrib.get('errors', 0))
                skipped = int(root.attrib.get('skipped', 0))
                passed = total - failures - errors - skipped
            
                # Writing to the special GitHub file variables
                with open(os.environ['GITHUB_ENV'], 'a') as f:
                    f.write(f'PASSED={passed}\n')
                    f.write(f'FAILED={failures + errors}\n')
                    f.write(f'SKIPPED={skipped}\n')
                    f.write(f'TOTAL={total}\n')
            except Exception as e:
                print(f'Error: {e}')
            "

      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>🚀 Test Report: ${{ github.repository }}</b>
            ✅ <b>Прошло:</b> ${{ env.PASSED }}
            ❌ <b>Упало:</b> ${{ env.FAILED }}
            ⏩ <b>Пропущено:</b> ${{ env.SKIPPED }}
            📝 <b>Всего:</b> ${{ env.TOTAL }}
            
            Job status: ${{ job.status }}
            📊 <b>Allure report:</b> <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/">View results</a>
            
            👤 Author: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}