name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-automation:
    runs-on: ubuntu-latest

    env:
      # --- Ссылаемся на Variables (твои TARGET_ENV и THREADS) ---
      TARGET_ENV: ${{ vars.TARGET_ENV }}
      THREADS: ${{ vars.THREADS }}

      GRAFANA_OTLP_ENDPOINT: ${{ secrets.GRAFANA_OTLP_ENDPOINT }}

      # ДОБАВЬ ЭТИ ДВЕ СТРОКИ:
      OTEL_LOG_LEVEL: debug
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENT: true

      BASE_URL_PROD: ${{ secrets.BASE_URL_PROD }}
      X_API_KEY_PROD: ${{ secrets.X_API_KEY_PROD }}
      URL_PREFIX_PROD: ${{ secrets.URL_PREFIX_PROD }}

      # User with history
      USER_PHONE_NUMBER_PROD: ${{ secrets.USER_PHONE_NUMBER_PROD }}
      USER_PASSWORD_PROD: ${{ secrets.USER_PASSWORD_PROD }}

      # User with empty history
      EMPTY_USER_PHONE_NUMBER_PROD: ${{ secrets.EMPTY_USER_PHONE_NUMBER_PROD }}
      EMPTY_USER_PASSWORD_PROD: ${{ secrets.EMPTY_USER_PASSWORD_PROD }}

      # Stage Environment
      BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
      X_API_KEY_STAGE: ${{ secrets.X_API_KEY_STAGE }}
      URL_PREFIX_STAGE: ${{ secrets.URL_PREFIX_STAGE }}
      USER_PHONE_STAGE: ${{ secrets.USER_PHONE_STAGE }}
      USER_PASS_STAGE: ${{ secrets.USER_PASS_STAGE }}
      EMPTY_USER_PHONE_STAGE: ${{ secrets.EMPTY_USER_PHONE_STAGE }}
      EMPTY_USER_PASS_STAGE: ${{ secrets.EMPTY_USER_PASS_STAGE }}

      # Database PROD
      DB_HOST_PROD: ${{ secrets.DB_HOST_PROD }}
      DB_PORT_PROD: ${{ secrets.DB_PORT_PROD }}
      DB_USER_PROD: ${{ secrets.DB_USER_PROD }}
      DB_PASSWORD_PROD: ${{ secrets.DB_PASSWORD_PROD }}
      DB_NAME_PROD: ${{ secrets.DB_NAME_PROD }}

      # Database STAGE
      DB_HOST_STAGE: ${{ secrets.DB_HOST_STAGE }}
      DB_PORT_STAGE: ${{ secrets.DB_PORT_STAGE }}
      DB_USER_STAGE: ${{ secrets.DB_USER_STAGE }}
      DB_PASSWORD_STAGE: ${{ secrets.DB_PASSWORD_STAGE }}
      DB_NAME_STAGE: ${{ secrets.DB_NAME_STAGE }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose build

      - name: Check Vars
        run: |
          echo "VARS TARGET_ENV: ${{ vars.TARGET_ENV }}"
          echo "VARS THREADS: ${{ vars.THREADS }}"
          printenv | grep -E 'TARGET_ENV|THREADS'

      - name: Run API Tests
        env:
          # GitHub автоматически подставит сюда всё из env джобы,
          # но мы добавим генерацию токена прямо здесь
          GRAFANA_INSTANCE_ID: ${{ secrets.GRAFANA_INSTANCE_ID }}
          GRAFANA_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
        run: |
          AUTH_RAW="${{ secrets.GRAFANA_INSTANCE_ID }}:${{ secrets.GRAFANA_CLOUD_TOKEN }}"
          export GRAFANA_AUTH_TOKEN=$(echo -n "$AUTH_RAW" | base64 -w 0)
          
          export TARGET_ENV=${{ vars.TARGET_ENV }}
          export THREADS=${{ vars.THREADS }}
          # Теперь Docker точно её увидит и ворнинг исчезнет
          docker compose up --build --exit-code-from api-tests

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 10

      - name: Load Allure history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clean history junk
        if: always()
        run: |
          if [ -d "gh-pages" ]; then
            cd gh-pages
            # Adding -A so to see hidden files like .env
            # Adding .nojekyll to the exception list  (GitHub needs it)
            ls -A | grep -vE '^[0-9]+$|history|index.html|last-history|favicon.ico|.nojekyll' | xargs rm -rf || true
            cd ..
          fi

      - name: Set Allure Custom Links Pattern
        if: always()
        run: |
          # 2. Використовуємо sudo tee для запису. 
          # Прапор -a означає append (дописати в кінець). 
          # Одинарні лапки навколо URL захищають від обробки спецсимволів шелом.
          echo 'allure.link.tms.pattern=https://github.com/SlavaPykhydko/QA_Demo_Project/blob/main/tests/api/sales/orders/online/TEST-CASES.md#%s' | sudo tee -a allure-results/environment.properties
    
          # 3. DEBUG: Перевіряємо, що записалося
          echo "--- Checking file content ---"
          sudo cat allure-results/environment.properties

      - name: Build Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
          force_orphan: true

      - name: Extract Test Stats
        if: always()
        run: |
          python <<EOF
          import xml.etree.ElementTree as ET
          import glob
          import os
      
          stats = {'total': 0, 'failures': 0, 'errors': 0, 'skipped': 0, 'passed': 0}
          
          # Find all files that start with report_ and end with .xml 
          files = glob.glob('junit-reports/report_*.xml')
          
          if not files:
              print("No report files found!")
          else:
              for report_file in files:
                  print(f"Parsing {report_file}...")
                  tree = ET.parse(report_file)
                  root = tree.getroot()
                  
                  # Sum data from all files
                  if root.tag == 'testsuites':
                      for suite in root.findall('testsuite'):
                          stats['total'] += int(suite.get('tests', 0))
                          stats['failures'] += int(suite.get('failures', 0))
                          stats['errors'] += int(suite.get('errors', 0))
                          stats['skipped'] += int(suite.get('skipped', 0))
                  else:
                      stats['total'] += int(root.get('tests', 0))
                      stats['failures'] += int(root.get('failures', 0))
                      stats['errors'] += int(root.get('errors', 0))
                      stats['skipped'] += int(root.get('skipped', 0))
      
              stats['passed'] = stats['total'] - stats['failures'] - stats['errors'] - stats['skipped']
      
          # Writing summary data to GITHUB_ENV
          with open(os.environ['GITHUB_ENV'], 'a') as f:
              f.write(f"PASSED={stats['passed']}\n")
              f.write(f"FAILED={stats['failures'] + stats['errors']}\n")
              f.write(f"SKIPPED={stats['skipped']}\n")
              f.write(f"TOTAL={stats['total']}\n")
          
          print(f"Combined stats: {stats}")
          EOF

      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>🚀 Project: ${{ github.repository }}</b>
            
            ✅ <b>Passed:</b> ${{ env.PASSED }}
            ❌ <b>Failed:</b> ${{ env.FAILED }}
            ⏩ <b>Skipped:</b> ${{ env.SKIPPED }}
            📝 <b>Total:</b> ${{ env.TOTAL }}
            
            Job status: ${{ job.status }}
            📊 <b>Allure report:</b> <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}/">View results (Run #${{ github.run_number }})</a>
            
            👤 Author: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}